export const GET_QUESTION = 'GET_QUESTION'

export const HANDLE_ANSWER_SELECTED = 'HANDLE_ANSWER_SELECTED'

export const SET_USER_ANSWER = 'SET_USER_ANSWER'

export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION'

export const SET_RESULTS = 'SET_RESULTS'